[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
bson = "2.7.0"
mongodb = "2.7.0"
tokio = "1.32.0"
dotenv = "0.15.0"